apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - port: 3007        # Service port
      targetPort: 3000  # Container port (Tomcat)
      protocol: TCP



# apiVersion: v1
# kind: Service
# metadata:
#   name: simple-nodejs-service
#   labels:
#     app: simple-nodejs-app
# spec:
#   type: NodePort
#   selector:
#     app: simple-nodejs-app
#   ports:
#     - protocol: TCP
#       port: 3002
#       targetPort: 3000
#       # nodePort: 31000
